# Generated by Django 4.1.1 on 2022-09-27 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
                ('index', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostalItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('departure_date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('LT', 'Letter'), ('PR', 'Parcel'), ('NP', 'Newspaper')], max_length=9)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='postapp.customer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='postapp.customer')),
            ],
            options={
                'db_table': 'postal_item',
                'ordering': ['-departure_date'],
            },
        ),
    ]
