# Generated by Django 4.1.1 on 2022-09-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalitem',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
